src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Controller\CartController;
use App\Model\ModifiedUserInterface;
use App\Model\ModifiedUserTrait;
use App\Model\OwnedInterface;
use App\Repository\CartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=CartRepository::class)
 */
class Cart implements ModifiedUserInterface, OwnedInterface
{
    use ModifiedUserTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="cart", cascade={"persist", "remove"})
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=CartItem::class, mappedBy="cart")
     */
    private $cartItem;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $totalPrice;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    public function __construct()
    {
        $this->cartItem = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|CartItem[]
     */
    public function getUncheckedCartItem()
    {
        $uncheckedCartItems = [];
        foreach ($this->getCartItem() as $item) {
            if ($item->getStatus() != CartController::CART_ITEM_STATUS_CHECKED_OUT) {
                array_push($uncheckedCartItems, $item);
            }
        }
        return $uncheckedCartItems;
    }

    /**
     * @return Collection|CartItem[]
     */
    public function getCartItem(): Collection
    {
        return $this->cartItem;
    }

    /**
     * @return Collection|CartItem[]
     */
    public function getCheckedCartItem()
    {
        $uncheckedCartItems = [];
        foreach ($this->getCartItem() as $item) {
            if ($item->getStatus() == CartController::CART_ITEM_STATUS_CHECKED_OUT) {
                array_push($uncheckedCartItems, $item);
            }
        }
        return $uncheckedCartItems;
    }

    public function addCartItem(CartItem $cartItem): self
    {
        if (!$this->cartItem->contains($cartItem)) {
            $this->cartItem[] = $cartItem;
            $cartItem->setCart($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): self
    {
        if ($this->cartItem->removeElement($cartItem)) {
            // set the owning side to null (unless already changed)
            if ($cartItem->getCart() === $this) {
                $cartItem->setCart(null);
            }
        }

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->totalPrice;
    }

    public function setTotalPrice(float $totalPrice): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getOwner(): ?User
    {
        return $this->user;
    }
}

templates/components/layout/header/components/_auth_links.html.twig
<li class="nav-item mr-2">
    <a class="nav-link whitespace-nowrap relative" href="{{ path('cart_index') }}">
                            <span aria-atomic="true" aria-live="polite"
                                  aria-label="shopping cart count"
                                  class="absolute top-1 -left-1 bg-red-500 text-white rounded-full h-5 w-5 flex justify-center items-center font-light"
                                  id="shopping_bag_count"
                            >
                                    {{ app.user.cart.uncheckedCartItem | length }}
                            </span>
        <i class="fas fa-shopping-bag text-2xl"></i>
    </a>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle flex justify-start items-center " data-bs-toggle="dropdown"
       href="#" role="button"
       aria-haspopup="true" aria-expanded="false">
        {% if app.user.avatar != null or  app.user.avatar != "" %}
            <img src="{{ asset('build/avatars/' ~ app.user.avatar ) }}"
                 alt=""
                 class="rounded-full w-8 h-8" style="min-width: 2rem"/>
        {% else %}
            <i class="fas fa-user-circle text-2xl "></i>
        {% endif %}
    </a>
    <div class="dropdown-menu font-semibold">

        {% if is_granted('ROLE_ADMIN') %}

            <a class="dropdown-item" href="{{ path('admin') }}">
                {{ 'app.nav.links.admin_panel'|trans }}
            </a>

        {% endif %}

        <a class="dropdown-item" href="{{ path('profile_index') }}">
            {{ 'app.nav.links.profile'|trans }}
        </a>

        <a class="dropdown-item flex justify-content-between" href="{{ path('cart_index') }}">
            {{ 'app.nav.links.cart'|trans }}
            <span aria-atomic="true" aria-live="polite"
                  aria-label="shopping cart count"
                  class=" bg-red-500 text-white rounded-full h-5 w-5 flex justify-center items-center font-light"
                  id="shopping_bag_count"
            >
                                {{ app.user.cart.uncheckedCartItem | length }}
                            </span>
        </a>

        <a class="dropdown-item" href="{{ path('wishlist') }}">
            {{ 'app.nav.links.wish_list'|trans }}
        </a>


        <a class="dropdown-item" href="{{ path('ticket_index') }}">
            {{ 'app.nav.links.ticket'|trans }}
        </a>


        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{{ path('app_logout') }}">
            <i class="fas fa-sign-out-alt"></i>
            {{ 'app.nav.links.logout'|trans }}
        </a>
    </div>
</li>

templates/components/layout/header/components/_locale_toggler.html.twig
{% set route = app.request.attributes.get('_route') %}
{% set route_params = app.request.attributes.get('_route_params') %}
{% set params = route_params|merge(app.request.query.all) %}

{% for locale in locales|split('|') %}
    {% if locale != app.request.locale %}

        <a class="dropdown-item font-semibold uppercase flex items-center"
           id="selectedLocale"
           href="{{ path(route, params|merge({ _locale: locale })) }}">
            <img class="w-4 mr-1.5"
                 src="{{ asset('build/img/flags/' ~ locale ~ '.png') }}"
                 alt="{{ locale }}">
            {{ locale }}
        </a>

    {% endif %}
{% endfor %}

templates/components/layout/header/components/_nav_links.html.twig
<li class="nav-item mr-4">
    <a class="nav-link" href="{{ path('home') }}">
        {{ 'app.nav.links.home'|trans }}
    </a>
</li>

<li class="nav-item mr-4">
    <a class="nav-link" href="{{ path('shop') }}">
        {{ 'app.nav.links.shop'|trans }}
    </a>
</li>

<li class="nav-item mr-4">
    <a class="nav-link" href="{{ path('contact') }}">
        {{ 'app.nav.links.contact'|trans }}
    </a>
</li>

<li class="nav-item mr-4">
    <a class="nav-link" href="{{ path('about') }}">
        {{ 'app.nav.links.about'|trans }}
    </a>
</li>

templates/components/layout/header/components/_nav_locale_dd.html.twig
<li class="nav-item dropdown locale_dropdown">
    <a class="nav-link dropdown-toggle flex justify-start items-center cursor-pointer uppercase"
       data-bs-toggle="dropdown"
    >
        <img class="w-4 mr-1.5"
             src="{{ asset('build/img/flags/' ~ app.request.locale ~ '.png') }}"
             alt="{{ app.request.locale }}">
        {{ app.request.locale }}
    </a>
    <div class="dropdown-menu font-semibold">

        {% include 'components/layout/header/components/_locale_toggler.html.twig' %}

    </div>
</li>

templates/components/layout/header/components/_nav_search.html.twig
<form class="flex max-w-lg p-1" method="GET" action="{{ path('search') }}">
    <input class="form-control rounded-l-sm"
           type="search"
           name="query"
           placeholder="{{ 'app.nav.search'|trans }}">

    <button class="btn rounded-r-sm bg-dark text-gray-200 hover:text-white " aria-label="search"
            type="submit">
        {{ 'app.nav.search'|trans }}
    </button>
</form>

templates/components/layout/header/components/_unauth_links.html.twig
<li class="nav-item mr-1">
    <a class="nav-link whitespace-nowrap" href="{{ path('app_login') }}">
        <i class="fas fa-fingerprint"></i>
        {{ 'app.nav.links.login'|trans }}
    </a>
</li>
<li class="nav-item -ml-1 mr-1">
    <a class="nav-link whitespace-nowrap" href="{{ path('app_register') }}">
        <i class="fas fa-user-plus"></i>
        {{ 'app.nav.links.register'|trans }}
    </a>
</li>